In [10]:
import torch
import torchvision
import numpy as np
import torchvision.transforms as transforms
from collections import defaultdict
from torch.utils.data import DataLoader, Subset

In [11]:
def get_MNIST_dirichlet_clients(
    data_root="./data",
    num_clients=10,
    alpha=0.5,
    batch_size=64,
    seed=42,
):
    # 1) CIFAR-10 transforms
    transform_train = transforms.Compose([
        transforms.RandomCrop(32, padding=4),
        transforms.RandomHorizontalFlip(),
        transforms.ToTensor(),
        transforms.Normalize(
            mean=(0.4914, 0.4822, 0.4465),
            std=(0.2023, 0.1994, 0.2010),
        ),
    ])

    # 2) Load CIFAR-10 train set
    trainset = torchvision.datasets.MNIST(
        root=data_root,
        train=True,
        download=True,
        transform=transform_train,
    )

    # 3) Get Dirichlet split indices per client
    client_idcs = dirichlet_split_noniid(
        dataset=trainset,
        num_clients=num_clients,
        alpha=alpha,
        seed=seed,
    )

    # 4) Wrap each client’s indices as a Subset + DataLoader
    client_loaders = {}
    for cid, idxs in client_idcs.items():
        subset = Subset(trainset, idxs)
        loader = DataLoader(
            subset,
            batch_size=batch_size,
            shuffle=True,
            num_workers=2,
            pin_memory=True,
        )
        client_loaders[cid] = loader

    return trainset, client_idcs, client_loaders


In [12]:
# ==============================
# Dirichlet non-IID splitter
# ==============================
def dirichlet_split_noniid(dataset, num_clients, alpha, seed=42):
    """
    Dirichlet label-distribution-based non-IID split.

    New semantics:
      - alpha = 0   -> IID split (random, equal-size).
      - alpha > 0   -> non-IID; larger alpha => more skewed (more non-IID).

    Returns:
        dict: {client_id: np.ndarray of indices}
    """
    np.random.seed(seed)

    n_samples = len(dataset)

    # ----- Special case: alpha = 0 => IID -----
    if alpha == 0:
        all_indices = np.random.permutation(n_samples)
        splits = np.array_split(all_indices, num_clients)
        client_indices = {
            cid: splits[cid] for cid in range(num_clients)
        }
        return client_indices

    # ----- alpha > 0 => Dirichlet-based non-IID -----
    # Map user alpha to Dirichlet concentration:
    # larger user alpha -> smaller conc -> more non-IID
    dirichlet_conc = 1.0 / alpha
    # (optional: clip to avoid extreme numerical issues)
    dirichlet_conc = float(np.clip(dirichlet_conc, 1e-3, 1e3))

    # Get labels generically
    if hasattr(dataset, "targets"):
        labels = np.array(dataset.targets)
    elif hasattr(dataset, "labels"):
        labels = np.array(dataset.labels)
    else:
        labels = np.array([dataset[i][1] for i in range(n_samples)])

    num_classes = int(labels.max()) + 1
    client_indices = defaultdict(list)

    # For each class, sample Dirichlet over clients
    for c in range(num_classes):
        class_idx = np.where(labels == c)[0]
        if len(class_idx) == 0:
            continue
        np.random.shuffle(class_idx)

        # Dirichlet proportions for this class across clients
        proportions = np.random.dirichlet(
            dirichlet_conc * np.ones(num_clients)
        )

        # Convert proportions to index splits
        split_points = (np.cumsum(proportions) * len(class_idx)).astype(int)
        class_split = np.split(class_idx, split_points[:-1])

        for client_id, idx in enumerate(class_split):
            client_indices[client_id].extend(idx.tolist())

    # Shuffle indices inside each client
    for client_id in range(num_clients):
        idx = np.array(client_indices[client_id], dtype=int)
        np.random.shuffle(idx)
        client_indices[client_id] = idx

    return client_indices


# ==============================
# CIFAR-10 + per-client loaders
# ==============================
def get_cifar10_dirichlet_clients(
    data_root="./data",
    num_clients=10,
    alpha=0.5,
    batch_size=64,
    seed=42,
):
    # 1) CIFAR-10 transforms
    transform_train = transforms.Compose([
        transforms.RandomCrop(32, padding=4),
        transforms.RandomHorizontalFlip(),
        transforms.ToTensor(),
        transforms.Normalize(
            mean=(0.4914, 0.4822, 0.4465),
            std=(0.2023, 0.1994, 0.2010),
        ),
    ])

    # 2) Load CIFAR-10 train set
    trainset = torchvision.datasets.CIFAR10(
        root=data_root,
        train=True,
        download=True,
        transform=transform_train,
    )

    # 3) Get Dirichlet split indices per client
    client_idcs = dirichlet_split_noniid(
        dataset=trainset,
        num_clients=num_clients,
        alpha=alpha,
        seed=seed,
    )

    # 4) Wrap each client’s indices as a Subset + DataLoader
    client_loaders = {}
    for cid, idxs in client_idcs.items():
        subset = Subset(trainset, idxs)
        loader = DataLoader(
            subset,
            batch_size=batch_size,
            shuffle=True,
            num_workers=2,
            pin_memory=True,
        )
        client_loaders[cid] = loader

    return trainset, client_idcs, client_loaders


# ==============================
# CIFAR-100 + per-client loaders
# ==============================
def get_cifar100_dirichlet_clients(
    data_root="./data",
    num_clients=10,
    alpha=0.5,
    batch_size=64,
    seed=42,
):
    # 1) CIFAR-100 transforms (same as CIFAR-10 usually)
    transform_train = transforms.Compose([
        transforms.RandomCrop(32, padding=4),
        transforms.RandomHorizontalFlip(),
        transforms.ToTensor(),
        transforms.Normalize(
            mean=(0.5071, 0.4867, 0.4408),
            std=(0.2675, 0.2565, 0.2761),
        ),
    ])

    # 2) Load CIFAR-100 train set
    trainset = torchvision.datasets.CIFAR100(
        root=data_root,
        train=True,
        download=True,
        transform=transform_train,
    )

    # 3) Get Dirichlet split indices per client
    client_idcs = dirichlet_split_noniid(
        dataset=trainset,
        num_clients=num_clients,
        alpha=alpha,
        seed=seed,
    )

    # 4) Wrap each client’s indices as a Subset + DataLoader
    client_loaders = {}
    for cid, idxs in client_idcs.items():
        subset = Subset(trainset, idxs)
        loader = DataLoader(
            subset,
            batch_size=batch_size,
            shuffle=True,
            num_workers=2,
            pin_memory=True,
        )
        client_loaders[cid] = loader

    return trainset, client_idcs, client_loaders

# =====================================
# Shakespeare + per-client loaders
# =====================================
def get_shakespeare_dirichlet_clients(
    dataset,
    num_clients=10,
    alpha=0.5,
    batch_size=32,
    seed=42,
):
    """
    dataset: a PyTorch Dataset for Shakespeare samples.
             Must expose labels via .targets/.labels or via dataset[i] -> (x, y).
    """
    # 1) Get Dirichlet split indices per client
    client_idcs = dirichlet_split_noniid(
        dataset=dataset,
        num_clients=num_clients,
        alpha=alpha,
        seed=seed,
    )

    # 2) Wrap each client’s indices as a Subset + DataLoader
    client_loaders = {}
    for cid, idxs in client_idcs.items():
        subset = Subset(dataset, idxs)
        loader = DataLoader(
            subset,
            batch_size=batch_size,
            shuffle=True,
            num_workers=2,
            pin_memory=True,
        )
        client_loaders[cid] = loader

    return dataset, client_idcs, client_loaders

In [15]:
# ==============================
# Example usage
# ==============================
if __name__ == "__main__":
    NUM_CLIENTS = 10
    ALPHA = 5  # smaller => more non-IID        # We decided to use alpha of 5 for the experiments

    trainset, client_idcs, client_loaders = get_MNIST_dirichlet_clients(
        data_root="/local/scratch/a/dalwis/single_agent_RL_for_pFL/data",
        num_clients=NUM_CLIENTS,
        alpha=ALPHA,
        batch_size=64,
        seed=123,
    )

    # Quick sanity check: print per-client sizes
    for cid, idxs in client_idcs.items():
        print(f"Client {cid}: {len(idxs)} samples")

    for i in range(NUM_CLIENTS):
      # Optional: check label distribution for a client
      labels = np.array(trainset.targets)
      cid = i
      client_labels = labels[client_idcs[cid]]
      print(f"Client {cid} label histogram:")
      print(np.bincount(client_labels, minlength=10))


Client 0: 13333 samples
Client 1: 6581 samples
Client 2: 8633 samples
Client 3: 2980 samples
Client 4: 852 samples
Client 5: 10778 samples
Client 6: 9289 samples
Client 7: 687 samples
Client 8: 3635 samples
Client 9: 3232 samples
Client 0 label histogram:
[1401 3556 2482    9  111    1   39 4137  304 1293]
Client 1 label histogram:
[  39  125  828 2326  900 2255   36   47   25    0]
Client 2 label histogram:
[   1    0  824    0   43 1779  980  162 4544  300]
Client 3 label histogram:
[   0    8  382  469   59   30    3   88  677 1264]
Client 4 label histogram:
[359   1  12 125   3   0  42  55 255   0]
Client 5 label histogram:
[   9 2469  223  424 4598  727  248    0    0 2080]
Client 6 label histogram:
[3460    0 1190 1027    3  449 1685 1130   12  333]
Client 7 label histogram:
[198   0   0   1   0 179   0   2  30 277]
Client 8 label histogram:
[   0  476   16 1740    0    0  759  643    0    1]
Client 9 label histogram:
[ 456  107    1   10  125    1 2126    1    4  401]


In [18]:
import os
import numpy as np
import torch
from torch.utils.data import Dataset, DataLoader, Subset
from torchvision import datasets, transforms
import pickle


# ============================================================
# 1. Make CIFAR-10 Dirichlet client splits
# ============================================================

def get_cifar10_dirichlet_clients(data_root, num_clients, alpha, batch_size, seed=123):

    np.random.seed(seed)
    torch.manual_seed(seed)

    transform = transforms.Compose([
        transforms.ToTensor()
    ])

    trainset = datasets.CIFAR10(root=data_root, train=True, download=True, transform=transform)

    labels = np.array(trainset.targets)
    num_classes = 10
    num_samples = len(trainset)

    # Group indices per class
    class_idx = [np.where(labels == c)[0] for c in range(num_classes)]

    client_idcs = {i: [] for i in range(num_clients)}

    # Dirichlet sampling
    for c in range(num_classes):
        np.random.shuffle(class_idx[c])
        proportions = np.random.dirichlet(alpha=[alpha] * num_clients)

        # Split indices for this class according to proportions
        proportions = (np.cumsum(proportions) * len(class_idx[c])).astype(int)[:-1]
        split = np.split(class_idx[c], proportions)

        for cid in range(num_clients):
            client_idcs[cid].extend(split[cid])

    # For reproducibility, shuffle each client's indices
    for cid in range(num_clients):
        np.random.shuffle(client_idcs[cid])

    # Build dataloaders
    client_loaders = {
        cid: DataLoader(Subset(trainset, client_idcs[cid]), batch_size=batch_size, shuffle=True)
        for cid in range(num_clients)
    }

    return trainset, client_idcs, client_loaders



# ============================================================
# 2. Save each client's dataset to disk
# ============================================================

def save_client_splits(save_dir, trainset, client_idcs):
    os.makedirs(save_dir, exist_ok=True)

    data = trainset.data        # numpy array (50000, 32, 32, 3)
    targets = np.array(trainset.targets)

    for cid, idxs in client_idcs.items():
        cid_dir = os.path.join(save_dir, f"client_{cid}")
        os.makedirs(cid_dir, exist_ok=True)

        client_data = data[idxs]
        client_targets = targets[idxs]

        # Save using numpy or pickle
        np.save(os.path.join(cid_dir, "data.npy"), client_data)
        np.save(os.path.join(cid_dir, "targets.npy"), client_targets)

        print(f"Saved Client {cid}: {len(idxs)} samples → {cid_dir}")



# ============================================================
# 3. Example usage
# ============================================================

if __name__ == "__main__":
    NUM_CLIENTS = 10
    ALPHA = 1       # More IID (We decided to use alpha of 5 for the experiments)
    BATCH_SIZE = 64

    trainset, client_idcs, client_loaders = get_cifar10_dirichlet_clients(
        data_root="/local/scratch/a/dalwis/single_agent_RL_for_pFL/data",
        num_clients=NUM_CLIENTS,
        alpha=1/ALPHA,
        batch_size=BATCH_SIZE,
        seed=123,
    )

    # Print sizes to confirm
    for cid, idxs in client_idcs.items():
        print(f"Client {cid}: {len(idxs)} samples")

    # Save the datasets
    save_client_splits(
        save_dir="/local/scratch/a/dalwis/single_agent_RL_for_pFL/data/CIFAR10/split_10_clients_alpha_1",
        trainset=trainset,
        client_idcs=client_idcs
    )


Files already downloaded and verified
Client 0: 4827 samples
Client 1: 5544 samples
Client 2: 3847 samples
Client 3: 4373 samples
Client 4: 4191 samples
Client 5: 4851 samples
Client 6: 4670 samples
Client 7: 5662 samples
Client 8: 5713 samples
Client 9: 6322 samples
Saved Client 0: 4827 samples → /local/scratch/a/dalwis/single_agent_RL_for_pFL/data/CIFAR10/split_10_clients_alpha_1/client_0
Saved Client 1: 5544 samples → /local/scratch/a/dalwis/single_agent_RL_for_pFL/data/CIFAR10/split_10_clients_alpha_1/client_1
Saved Client 2: 3847 samples → /local/scratch/a/dalwis/single_agent_RL_for_pFL/data/CIFAR10/split_10_clients_alpha_1/client_2
Saved Client 3: 4373 samples → /local/scratch/a/dalwis/single_agent_RL_for_pFL/data/CIFAR10/split_10_clients_alpha_1/client_3
Saved Client 4: 4191 samples → /local/scratch/a/dalwis/single_agent_RL_for_pFL/data/CIFAR10/split_10_clients_alpha_1/client_4
Saved Client 5: 4851 samples → /local/scratch/a/dalwis/single_agent_RL_for_pFL/data/CIFAR10/split_10_c